// ─── DATA MODULE ─────────────────────────────────────────────────────────────
// All raw data: nodes, edges, descriptions, domains, domain centers.

export const DOMAINS = {
  "Formal Sciences":         { color: "#c8b89a", cx: 0.5,  cy: 0.2  },  // warm parchment
  "Physical Sciences":       { color: "#8faa8b", cx: 0.75, cy: 0.3  },  // sage green
  "Earth & Space":           { color: "#7a9e7e", cx: 0.65, cy: 0.55 },  // muted forest
  "Life Sciences":           { color: "#6b9e6e", cx: 0.55, cy: 0.72 },  // deeper moss
  "Chemistry":               { color: "#b5c99a", cx: 0.82, cy: 0.5  },  // light olive
  "Medicine & Health":       { color: "#c67d4a", cx: 0.15, cy: 0.38 },  // burnt sienna
  "Social Sciences":         { color: "#c9a84c", cx: 0.38, cy: 0.35 },  // goldenrod
  "Humanities":              { color: "#b8956a", cx: 0.42, cy: 0.52 },  // warm tan
  "Arts & Design":           { color: "#9b6b3a", cx: 0.3,  cy: 0.62 },  // dark umber
  "Engineering & Tech":      { color: "#7a9aa8", cx: 0.7,  cy: 0.18 },  // slate blue-grey
  "Interdisciplinary":       { color: "#a09070", cx: 0.5,  cy: 0.5  },  // warm greige
  "Esoteric & Occult":       { color: "#6b5a7e", cx: 0.18, cy: 0.65 },  // muted plum
  "Contemplative Traditions":{ color: "#c48a3f", cx: 0.22, cy: 0.82 },  // amber ochre
  "Indigenous & Traditional":{ color: "#7d9c5a", cx: 0.42, cy: 0.88 },  // earthy green
  "Consciousness & Fringe":  { color: "#8b6f5e", cx: 0.72, cy: 0.82 },  // warm clay
};

export const NODES_RAW = [
  // Formal Sciences
  ["Mathematics",       "Formal Sciences", 22],
  ["Statistics",        "Formal Sciences", 15],
  ["Logic",             "Formal Sciences", 13],
  ["Information Theory","Formal Sciences", 11],
  ["Probability Theory","Formal Sciences", 12],
  ["Graph Theory",      "Formal Sciences", 10],
  ["Number Theory",     "Formal Sciences", 10],
  ["Topology",          "Formal Sciences", 10],
  ["Algebra",           "Formal Sciences", 11],
  ["Calculus",          "Formal Sciences", 10],
  ["Geometry",          "Formal Sciences", 10],
  ["Combinatorics",     "Formal Sciences", 9],
  ["Set Theory",        "Formal Sciences", 9],
  ["Category Theory",   "Formal Sciences", 8],
  ["Numerical Analysis","Formal Sciences", 9],

  // Physical Sciences
  ["Physics",           "Physical Sciences", 22],
  ["Quantum Mechanics", "Physical Sciences", 16],
  ["Thermodynamics",    "Physical Sciences", 13],
  ["Electromagnetism",  "Physical Sciences", 13],
  ["Relativity",        "Physical Sciences", 13],
  ["Optics",            "Physical Sciences", 11],
  ["Acoustics",         "Physical Sciences", 10],
  ["Particle Physics",  "Physical Sciences", 13],
  ["Nuclear Physics",   "Physical Sciences", 12],
  ["Astrophysics",      "Physical Sciences", 14],
  ["Cosmology",         "Physical Sciences", 13],
  ["Statistical Physics","Physical Sciences",12],
  ["Condensed Matter",  "Physical Sciences", 11],
  ["Plasma Physics",    "Physical Sciences", 10],

  // Earth & Space
  ["Geology",           "Earth & Space", 14],
  ["Oceanography",      "Earth & Space", 12],
  ["Meteorology",       "Earth & Space", 12],
  ["Climatology",       "Earth & Space", 13],
  ["Hydrology",         "Earth & Space", 11],
  ["Seismology",        "Earth & Space", 10],
  ["Volcanology",       "Earth & Space", 9],
  ["Glaciology",        "Earth & Space", 9],
  ["Paleontology",      "Earth & Space", 12],
  ["Mineralogy",        "Earth & Space", 10],
  ["Soil Science",      "Earth & Space", 10],
  ["Geography",         "Earth & Space", 13],
  ["Cartography",       "Earth & Space", 10],
  ["Astronomy",         "Earth & Space", 14],

  // Life Sciences
  ["Biology",           "Life Sciences", 22],
  ["Ecology",           "Life Sciences", 16],
  ["Genetics",          "Life Sciences", 16],
  ["Evolutionary Biology","Life Sciences",16],
  ["Microbiology",      "Life Sciences", 14],
  ["Zoology",           "Life Sciences", 13],
  ["Botany",            "Life Sciences", 13],
  ["Neuroscience",      "Life Sciences", 16],
  ["Cell Biology",      "Life Sciences", 14],
  ["Molecular Biology", "Life Sciences", 15],
  ["Biochemistry",      "Life Sciences", 15],
  ["Marine Biology",    "Life Sciences", 12],
  ["Ethology",          "Life Sciences", 11],
  ["Physiology",        "Life Sciences", 14],
  ["Immunology",        "Life Sciences", 14],
  ["Virology",          "Life Sciences", 13],
  ["Taxonomy",          "Life Sciences", 11],
  ["Biodiversity",      "Life Sciences", 12],

  // Chemistry
  ["Chemistry",         "Chemistry", 20],
  ["Organic Chemistry", "Chemistry", 16],
  ["Inorganic Chemistry","Chemistry", 14],
  ["Physical Chemistry","Chemistry", 15],
  ["Analytical Chemistry","Chemistry",14],
  ["Electrochemistry",  "Chemistry", 12],
  ["Polymer Chemistry", "Chemistry", 11],
  ["Geochemistry",      "Chemistry", 11],
  ["Astrochemistry",    "Chemistry", 10],
  ["Computational Chemistry","Chemistry",11],
  ["Toxicology",        "Chemistry", 13],
  ["Pharmacology",      "Chemistry", 14],

  // Medicine & Health
  ["Medicine",          "Medicine & Health", 22],
  ["Anatomy",           "Medicine & Health", 14],
  ["Pathology",         "Medicine & Health", 14],
  ["Surgery",           "Medicine & Health", 13],
  ["Psychiatry",        "Medicine & Health", 14],
  ["Epidemiology",      "Medicine & Health", 14],
  ["Nutrition",         "Medicine & Health", 12],
  ["Pharmacology (Med)","Medicine & Health", 13],
  ["Dentistry",         "Medicine & Health", 11],
  ["Nursing",           "Medicine & Health", 11],
  ["Public Health",     "Medicine & Health", 14],
  ["Genetics (Med)",    "Medicine & Health", 13],
  ["Oncology",          "Medicine & Health", 13],
  ["Cardiology",        "Medicine & Health", 12],
  ["Neurology",         "Medicine & Health", 13],
  ["Dermatology",       "Medicine & Health", 11],
  ["Radiology",         "Medicine & Health", 12],
  ["Biotechnology",     "Medicine & Health", 14],

  // Social Sciences
  ["Sociology",         "Social Sciences", 18],
  ["Psychology",        "Social Sciences", 18],
  ["Economics",         "Social Sciences", 18],
  ["Anthropology",      "Social Sciences", 16],
  ["Political Science", "Social Sciences", 16],
  ["Demography",        "Social Sciences", 13],
  ["Criminology",       "Social Sciences", 13],
  ["International Relations","Social Sciences",14],
  ["Cultural Studies",  "Social Sciences", 13],
  ["Social Psychology", "Social Sciences", 14],
  ["Cognitive Science", "Social Sciences", 16],
  ["Behavioral Economics","Social Sciences",14],
  ["Urban Studies",     "Social Sciences", 12],
  ["Education Theory",  "Social Sciences", 13],
  ["Communication",     "Social Sciences", 13],
  ["Human Geography",   "Social Sciences", 12],

  // Humanities
  ["Philosophy",        "Humanities", 20],
  ["History",           "Humanities", 18],
  ["Literature",        "Humanities", 16],
  ["Linguistics",       "Humanities", 16],
  ["Ethics",            "Humanities", 15],
  ["Aesthetics",        "Humanities", 12],
  ["Religion",          "Humanities", 14],
  ["Mythology",         "Humanities", 12],
  ["Archaeology",       "Humanities", 14],
  ["Classics",          "Humanities", 12],
  ["Law",               "Humanities", 16],
  ["Epistemology",      "Humanities", 13],
  ["Metaphysics",       "Humanities", 12],
  ["Semiotics",         "Humanities", 11],
  ["Hermeneutics",      "Humanities", 10],
  ["Political Philosophy","Humanities", 14],

  // Arts & Design
  ["Music",             "Arts & Design", 16],
  ["Visual Art",        "Arts & Design", 15],
  ["Architecture",      "Arts & Design", 16],
  ["Film & Cinema",     "Arts & Design", 14],
  ["Theater",           "Arts & Design", 13],
  ["Dance",             "Arts & Design", 11],
  ["Photography",       "Arts & Design", 12],
  ["Graphic Design",    "Arts & Design", 13],
  ["Industrial Design", "Arts & Design", 12],
  ["Fashion Design",    "Arts & Design", 11],
  ["Narrative Design",  "Arts & Design", 11],
  ["Game Design",       "Arts & Design", 13],
  ["Urban Design",      "Arts & Design", 12],

  // Engineering & Tech
  ["Computer Science",  "Engineering & Tech", 22],
  ["Electrical Engineering","Engineering & Tech",16],
  ["Mechanical Engineering","Engineering & Tech",16],
  ["Civil Engineering", "Engineering & Tech", 14],
  ["Chemical Engineering","Engineering & Tech",14],
  ["Aerospace Engineering","Engineering & Tech",14],
  ["Materials Science", "Engineering & Tech", 14],
  ["Robotics",          "Engineering & Tech", 15],
  ["Artificial Intelligence","Engineering & Tech",18],
  ["Machine Learning",  "Engineering & Tech", 17],
  ["Software Engineering","Engineering & Tech",16],
  ["Cryptography",      "Engineering & Tech", 13],
  ["Telecommunications","Engineering & Tech", 13],
  ["Nanotechnology",    "Engineering & Tech", 13],
  ["Biomedical Engineering","Engineering & Tech",14],
  ["Environmental Engineering","Engineering & Tech",13],
  ["Systems Theory",    "Engineering & Tech", 13],

  // Interdisciplinary
  ["Cognitive Science (Interdis.)","Interdisciplinary",14],
  ["Complexity Science","Interdisciplinary", 14],
  ["Systems Biology",   "Interdisciplinary", 13],
  ["Bioinformatics",    "Interdisciplinary", 14],
  ["Environmental Science","Interdisciplinary",16],
  ["Science & Tech Studies","Interdisciplinary",12],
  ["Philosophy of Science","Interdisciplinary",13],
  ["Philosophy of Mind","Interdisciplinary", 15],
  ["Neurophilosophy",   "Interdisciplinary", 12],
  ["Data Science",      "Interdisciplinary", 16],
  ["Cybernetics",       "Interdisciplinary", 12],
  ["Information Science","Interdisciplinary", 13],
  ["Science Communication","Interdisciplinary",11],

  // Esoteric & Occult
  ["Hermeticism",       "Esoteric & Occult", 14],
  ["Alchemy",           "Esoteric & Occult", 13],
  ["Kabbalah",          "Esoteric & Occult", 13],
  ["Astrology",         "Esoteric & Occult", 12],
  ["Tarot",             "Esoteric & Occult", 10],
  ["Numerology",        "Esoteric & Occult", 10],
  ["Sacred Geometry",   "Esoteric & Occult", 12],
  ["Gnosticism",        "Esoteric & Occult", 13],
  ["Theosophy",         "Esoteric & Occult", 12],
  ["Ceremonial Magic",  "Esoteric & Occult", 11],
  ["Divination",        "Esoteric & Occult", 11],
  ["Neoplatonism",      "Esoteric & Occult", 13],
  ["Rosicrucianism",    "Esoteric & Occult", 10],
  ["Freemasonry",       "Esoteric & Occult", 11],
  ["Mystery Traditions","Esoteric & Occult", 12],

  // Contemplative Traditions
  ["Meditation",        "Contemplative Traditions", 14],
  ["Yoga Philosophy",   "Contemplative Traditions", 13],
  ["Zen Buddhism",      "Contemplative Traditions", 13],
  ["Sufism",            "Contemplative Traditions", 13],
  ["Christian Mysticism","Contemplative Traditions",12],
  ["Taoism",            "Contemplative Traditions", 14],
  ["Advaita Vedanta",   "Contemplative Traditions", 13],
  ["Contemplative Prayer","Contemplative Traditions",11],
  ["Tantra",            "Contemplative Traditions", 12],
  ["Shamanic Traditions","Contemplative Traditions",12],
  ["Lucid Dreaming",    "Contemplative Traditions", 10],
  ["Breathwork",        "Contemplative Traditions", 10],

  // Indigenous & Traditional Knowledge
  ["Indigenous Cosmology","Indigenous & Traditional", 13],
  ["Ethnobotany",        "Indigenous & Traditional", 14],
  ["Traditional Medicine","Indigenous & Traditional", 14],
  ["Oral Traditions",    "Indigenous & Traditional", 13],
  ["Animism",            "Indigenous & Traditional", 12],
  ["Totemism",           "Indigenous & Traditional", 11],
  ["Land Knowledge",     "Indigenous & Traditional", 12],
  ["Ethnoastronomy",     "Indigenous & Traditional", 11],
  ["Ritual Studies",     "Indigenous & Traditional", 12],
  ["Ancestor Veneration","Indigenous & Traditional", 11],
  ["Sacred Ecology",     "Indigenous & Traditional", 12],
  ["Ethnoarchaeology",   "Indigenous & Traditional", 11],

  // Consciousness & Fringe Science
  ["Consciousness Studies","Consciousness & Fringe", 16],
  ["Parapsychology",     "Consciousness & Fringe", 12],
  ["Psychedelic Science","Consciousness & Fringe", 14],
  ["Near-Death Studies", "Consciousness & Fringe", 11],
  ["Dream Studies",      "Consciousness & Fringe", 12],
  ["Anomalous Cognition","Consciousness & Fringe", 10],
  ["Quantum Mind Theory","Consciousness & Fringe", 12],
  ["Morphic Resonance",  "Consciousness & Fringe", 10],
  ["Noetics",            "Consciousness & Fringe", 11],
  ["Integral Theory",    "Consciousness & Fringe", 12],
  ["Transpersonal Psychology","Consciousness & Fringe",13],
  ["Chronobiology",      "Consciousness & Fringe", 11],
];

export const NODE_DESCRIPTIONS = {
  // Formal Sciences
  "Mathematics": "The abstract study of number, quantity, structure, and space — the universal language underlying all quantitative reasoning.",
  "Statistics": "The science of collecting, analyzing, and interpreting data to reveal patterns and support decisions under uncertainty.",
  "Logic": "The formal study of valid inference and correct reasoning, foundational to mathematics, philosophy, and computer science.",
  "Information Theory": "Quantifies information, entropy, and communication limits — the theoretical backbone of all digital technology.",
  "Probability Theory": "The mathematical framework for reasoning about chance, uncertainty, and random phenomena.",
  "Graph Theory": "Studies networks of nodes and edges — essential to understanding relationships in biology, society, and computation.",
  "Number Theory": "The pure mathematics of integers and their properties, hiding extraordinary depth beneath apparent simplicity.",
  "Topology": "Studies properties preserved under continuous deformation — shapes without rulers, space without distance.",
  "Algebra": "Generalizes arithmetic through symbols and structures, revealing deep patterns across mathematics.",
  "Calculus": "The mathematics of continuous change — rates, areas, and accumulation — engine of physics and engineering.",
  "Geometry": "The study of shape, size, and spatial relationships, from Euclid's axioms to curved spacetime.",
  "Combinatorics": "Counts and arranges discrete structures, underpinning cryptography, probability, and algorithm design.",
  "Set Theory": "The foundational language of mathematics, examining collections of objects and their relationships.",
  "Category Theory": "An abstract framework unifying mathematical structures through morphisms and functors — mathematics about mathematics.",
  "Numerical Analysis": "Develops algorithms to approximate mathematical problems computationally with controlled precision.",

  // Physical Sciences
  "Physics": "The fundamental science of matter, energy, and the forces governing the universe from quarks to cosmos.",
  "Quantum Mechanics": "Describes reality at subatomic scales — probabilistic, non-local, and deeply counterintuitive.",
  "Thermodynamics": "Laws governing heat, work, and energy — including entropy's arrow pointing only toward disorder.",
  "Electromagnetism": "Unifies electricity and magnetism; governs light, radio waves, and all electronic technology.",
  "Relativity": "Einstein's rewriting of space, time, and gravity — mass curves spacetime, time dilates with speed.",
  "Optics": "The physics of light — reflection, refraction, diffraction, and the wave-particle duality of photons.",
  "Acoustics": "The science of sound waves, vibration, and their perception — from music theory to sonar.",
  "Particle Physics": "Probes the fundamental constituents of matter — quarks, leptons, and the forces between them.",
  "Nuclear Physics": "Studies the atomic nucleus, nuclear forces, fission, fusion, and radioactive decay.",
  "Astrophysics": "Applies physics to understand stars, galaxies, black holes, and the large-scale universe.",
  "Cosmology": "Studies the origin, structure, and ultimate fate of the universe as a whole.",
  "Statistical Physics": "Uses probability to explain bulk properties of matter emerging from microscopic interactions.",
  "Condensed Matter": "The richest branch of physics — explains superconductivity, magnetism, crystals, and phase transitions.",
  "Plasma Physics": "Studies ionized gas, the most common state of visible matter in the universe.",

  // Earth & Space
  "Geology": "Reads Earth's history through rocks, minerals, and tectonic forces spanning billions of years.",
  "Oceanography": "Explores the physics, chemistry, biology, and geology of Earth's oceans.",
  "Meteorology": "The science of atmospheric dynamics, weather patterns, and short-term climate phenomena.",
  "Climatology": "Studies long-term patterns and changes in Earth's climate systems.",
  "Hydrology": "Examines the movement, distribution, and quality of water across the planet.",
  "Seismology": "Studies earthquakes and seismic waves to probe Earth's deep interior structure.",
  "Volcanology": "Investigates volcanic processes, eruptions, and magma dynamics.",
  "Glaciology": "Studies ice sheets, glaciers, and their role in Earth's climate and sea level.",
  "Paleontology": "Reconstructs ancient life from fossils, bridging geology and evolutionary biology.",
  "Mineralogy": "Classifies and characterizes minerals — their crystal structure, composition, and formation.",
  "Soil Science": "Studies soil formation, composition, and ecology — the thin living skin of the planet.",
  "Geography": "Maps and analyzes the spatial relationships between human societies and physical environments.",
  "Cartography": "The art and science of making maps — representation, projection, and spatial communication.",
  "Astronomy": "Observes and measures celestial objects — stars, planets, galaxies, and cosmic phenomena.",

  // Life Sciences
  "Biology": "The science of life — studying organisms from molecules to ecosystems in all their complexity.",
  "Ecology": "Examines relationships between organisms and their environments, including population and community dynamics.",
  "Genetics": "Studies heredity and variation through genes, chromosomes, and the mechanisms of inheritance.",
  "Evolutionary Biology": "Explains the diversity of life through descent with modification, natural selection, and genetic drift.",
  "Microbiology": "Investigates microscopic organisms — bacteria, archaea, fungi — and their vast ecological roles.",
  "Zoology": "The systematic study of animals — their behavior, physiology, classification, and evolution.",
  "Botany": "The science of plants, their biology, ecology, diversity, and significance to life on Earth.",
  "Neuroscience": "Investigates the nervous system — from single neurons to cognition, emotion, and consciousness.",
  "Cell Biology": "Studies the cell as life's fundamental unit — structure, function, signaling, and division.",
  "Molecular Biology": "Examines biological processes at the molecular level — DNA, RNA, protein synthesis.",
  "Biochemistry": "Explores the chemistry of life — metabolic pathways, enzymes, and biomolecular interactions.",
  "Marine Biology": "Studies life in ocean environments — from hydrothermal vent ecosystems to whale migration.",
  "Ethology": "Investigates animal behavior in natural settings — instinct, learning, and social organization.",
  "Physiology": "Studies the functions and mechanisms of living organisms and their organ systems.",
  "Immunology": "Examines the immune system's recognition and defense against pathogens and disease.",
  "Virology": "Studies viruses — their structure, replication, and complex relationships with host organisms.",
  "Taxonomy": "Classifies and names living organisms, creating the universal language of biodiversity.",
  "Biodiversity": "Quantifies and studies the variety of life at genetic, species, and ecosystem levels.",

  // Chemistry
  "Chemistry": "Studies matter's composition, properties, and transformations — the central science bridging physics and biology.",
  "Organic Chemistry": "The chemistry of carbon compounds — the molecular basis of life and synthetic materials.",
  "Inorganic Chemistry": "Studies non-carbon compounds — metals, minerals, and coordination complexes.",
  "Physical Chemistry": "Applies physics to chemical systems — thermodynamics, kinetics, and quantum chemistry.",
  "Analytical Chemistry": "Identifies and quantifies chemical substances using sophisticated measurement techniques.",
  "Electrochemistry": "Studies chemical reactions driven by or producing electrical energy — batteries, corrosion, biosensors.",
  "Polymer Chemistry": "Designs and studies large chain molecules — plastics, rubber, proteins, and DNA.",
  "Geochemistry": "Applies chemistry to understand Earth's composition, geological processes, and elemental cycles.",
  "Astrochemistry": "Studies molecules in space — interstellar clouds, comets, and the chemistry of planetary formation.",
  "Computational Chemistry": "Uses algorithms and simulation to model molecular behavior and chemical reactions.",
  "Toxicology": "Studies the adverse effects of chemical substances on living organisms.",
  "Pharmacology": "Investigates how drugs interact with biological systems — mechanisms, effects, and dosage.",

  // Medicine & Health
  "Medicine": "The science and practice of diagnosing, treating, and preventing disease in humans.",
  "Anatomy": "Maps the structure of the human body — organs, tissues, and their spatial relationships.",
  "Pathology": "Studies the causes and mechanisms of disease at cellular and molecular levels.",
  "Surgery": "Treats disease and injury through direct physical intervention on the body.",
  "Psychiatry": "Diagnoses and treats mental disorders through biological, psychological, and social frameworks.",
  "Epidemiology": "Tracks disease distribution in populations to identify causes and guide public health policy.",
  "Nutrition": "Studies how diet and nutrients affect health, metabolism, and disease prevention.",
  "Pharmacology (Med)": "Applies drug science to clinical treatment — efficacy, safety, and pharmacokinetics.",
  "Dentistry": "Diagnoses and treats conditions of the oral cavity, teeth, and jaw.",
  "Nursing": "A clinical discipline focused on patient care, advocacy, and health promotion.",
  "Public Health": "Protects and improves health at population scale through policy, education, and prevention.",
  "Genetics (Med)": "Applies genetic knowledge to diagnose inherited disorders and guide personalized medicine.",
  "Oncology": "Diagnoses and treats cancer — a field transformed by molecular biology and immunotherapy.",
  "Cardiology": "Specializes in heart and cardiovascular system disorders — medicine's highest-stakes domain.",
  "Neurology": "Clinical care for nervous system disorders — stroke, epilepsy, neurodegeneration.",
  "Dermatology": "Studies and treats skin conditions — the body's largest organ and first immune barrier.",
  "Radiology": "Uses imaging technologies to visualize internal anatomy and guide diagnosis and treatment.",
  "Biotechnology": "Engineers biological systems for medical, agricultural, and industrial applications.",

  // Social Sciences
  "Sociology": "Examines social structures, institutions, and the collective patterns shaping human behavior.",
  "Psychology": "Studies behavior and mental processes — cognition, emotion, personality, and social influence.",
  "Economics": "Analyzes how individuals and societies allocate scarce resources under incentive and constraint.",
  "Anthropology": "Explores human diversity across cultures, time periods, and biological evolution.",
  "Political Science": "Studies political systems, power, governance, and the theory and practice of government.",
  "Demography": "Analyzes population dynamics — birth, death, migration, and their social consequences.",
  "Criminology": "Examines crime, deviance, criminal justice, and the social roots of lawbreaking.",
  "International Relations": "Studies interactions between states, international organizations, and global power dynamics.",
  "Cultural Studies": "Critically examines culture, representation, identity, and the politics of meaning.",
  "Social Psychology": "Explores how social contexts shape individual thought, feeling, and behavior.",
  "Cognitive Science": "An interdisciplinary study of mind, intelligence, and mental processes across species and machines.",
  "Behavioral Economics": "Blends psychology and economics to explain how humans actually make decisions.",
  "Urban Studies": "Examines the design, governance, inequality, and lived experience of cities.",
  "Education Theory": "Studies how learning occurs and how knowledge should be transmitted across generations.",
  "Communication": "Analyzes how meaning is created and shared through language, media, and symbol.",
  "Human Geography": "Studies the spatial patterns of human activity, culture, and interaction with environment.",

  // Humanities
  "Philosophy": "Pursues fundamental questions about existence, knowledge, value, reason, and mind.",
  "History": "Reconstructs and interprets the human past through evidence, narrative, and critical analysis.",
  "Literature": "Studies written works as art — language, narrative, meaning, and cultural expression.",
  "Linguistics": "The scientific study of language — structure, acquisition, change, and cognitive underpinnings.",
  "Ethics": "Examines what is morally right, the foundations of value, and how we ought to live.",
  "Aesthetics": "Philosophical inquiry into beauty, art, taste, and the nature of aesthetic experience.",
  "Religion": "Studies religious belief, practice, and institutions across human cultures and history.",
  "Mythology": "Examines traditional narratives that encode a culture's cosmology, values, and origins.",
  "Archaeology": "Recovers and interprets material culture to reconstruct past human lives and societies.",
  "Classics": "Scholarship on ancient Greek and Roman language, literature, history, and thought.",
  "Law": "The system of rules governing society — its creation, interpretation, and enforcement.",
  "Epistemology": "Asks what knowledge is, how we acquire it, and what its limits are.",
  "Metaphysics": "Investigates the fundamental nature of reality — being, time, causation, identity.",
  "Semiotics": "Studies signs, symbols, and the processes by which meaning is created and communicated.",
  "Hermeneutics": "The theory and methodology of text interpretation — from scripture to all forms of meaning.",
  "Political Philosophy": "Examines the foundations of political authority, justice, rights, and the ideal society.",

  // Arts & Design
  "Music": "The art of organizing sound in time — melody, harmony, rhythm, and the expression of emotion.",
  "Visual Art": "Creates meaning and experience through visual media — painting, sculpture, and conceptual work.",
  "Architecture": "Designs built environments that balance structural necessity, function, and aesthetic vision.",
  "Film & Cinema": "A narrative and visual art form that shapes culture, identity, and collective memory.",
  "Theater": "Live performance combining drama, movement, voice, and design to embody human experience.",
  "Dance": "Expression through movement — the body as instrument of narrative, emotion, and culture.",
  "Photography": "Captures light to document reality and construct meaning through framing and moment.",
  "Graphic Design": "Solves visual communication problems through typography, image, and composition.",
  "Industrial Design": "Creates objects for human use, balancing function, manufacturability, and aesthetics.",
  "Fashion Design": "Designs clothing as cultural artifact, identity expression, and aesthetic object.",
  "Narrative Design": "Structures story across interactive and non-linear media — games, experience design.",
  "Game Design": "Crafts interactive systems that produce meaningful play, challenge, and narrative experience.",
  "Urban Design": "Shapes the public realm — streets, squares, and the spaces between buildings.",

  // Engineering & Tech
  "Computer Science": "Studies computation, algorithms, data structures, and the theoretical limits of machines.",
  "Electrical Engineering": "Designs systems that generate, transmit, and use electrical energy and signals.",
  "Mechanical Engineering": "Applies physics to design machines, structures, and thermal systems.",
  "Civil Engineering": "Designs infrastructure — bridges, roads, dams — that shapes how civilization functions.",
  "Chemical Engineering": "Converts raw materials into valuable products through industrial-scale chemical processes.",
  "Aerospace Engineering": "Designs aircraft and spacecraft operating in atmosphere and beyond.",
  "Materials Science": "Engineers the properties of matter to create new materials with targeted behaviors.",
  "Robotics": "Combines mechanics, electronics, and AI to create machines that sense and act autonomously.",
  "Artificial Intelligence": "Builds systems capable of tasks requiring human-like intelligence — reasoning, perception, language.",
  "Machine Learning": "Enables computers to learn patterns from data without being explicitly programmed.",
  "Software Engineering": "The disciplined design, development, and maintenance of complex software systems.",
  "Cryptography": "Secures communication through mathematical encoding, enabling privacy in a digital world.",
  "Telecommunications": "Engineering the transmission of information across distance through signals and networks.",
  "Nanotechnology": "Manipulates matter at atomic scales to create materials and devices with novel properties.",
  "Biomedical Engineering": "Applies engineering principles to medicine — prosthetics, imaging, drug delivery systems.",
  "Environmental Engineering": "Designs solutions to environmental pollution, waste management, and sustainable infrastructure.",
  "Systems Theory": "Studies how complex systems behave through feedback, emergence, and self-organization.",

  // Interdisciplinary
  "Cognitive Science (Interdis.)": "Synthesizes neuroscience, psychology, AI, linguistics, and philosophy to understand the mind.",
  "Complexity Science": "Studies how simple rules produce emergent complexity — from ant colonies to financial markets.",
  "Systems Biology": "Models biological organisms as integrated networks of interacting components.",
  "Bioinformatics": "Applies computational methods to analyze genomic, proteomic, and biological sequence data.",
  "Environmental Science": "Integrates natural sciences to understand environmental problems and guide solutions.",
  "Science & Tech Studies": "Examines how science and technology shape and are shaped by society and culture.",
  "Philosophy of Science": "Investigates the methods, foundations, and implications of scientific inquiry.",
  "Philosophy of Mind": "Examines consciousness, mental states, and the relationship between mind and brain.",
  "Neurophilosophy": "Bridges neuroscience and philosophy to address consciousness, free will, and identity.",
  "Data Science": "Extracts insight from large, complex datasets using statistics, computation, and domain expertise.",
  "Cybernetics": "Studies control and communication in animals and machines — the science of feedback systems.",
  "Information Science": "Manages, retrieves, and organizes knowledge across libraries, databases, and digital systems.",
  "Science Communication": "Translates complex scientific ideas for public understanding and informed democratic discourse.",

  // Esoteric & Occult
  "Hermeticism": "A philosophical tradition rooted in ancient Egypt and Greece — 'as above, so below' — linking macrocosm to microcosm.",
  "Alchemy": "The precursor to chemistry, pursuing transformation of base metals into gold and of the self into wisdom.",
  "Kabbalah": "A mystical Jewish tradition mapping divine emanation through the Sefirot, seeking hidden dimensions of scripture.",
  "Astrology": "Correlates celestial configurations with earthly events and human character — one of humanity's oldest symbolic systems.",
  "Tarot": "A symbolic system of 78 archetypes used for divination, psychological reflection, and narrative.",
  "Numerology": "Assigns symbolic meaning to numbers and their relationship to names, dates, and cosmic patterns.",
  "Sacred Geometry": "Attributes spiritual significance to geometric ratios — the Fibonacci spiral, Platonic solids, the golden mean.",
  "Gnosticism": "Ancient dualist traditions teaching that the material world is flawed and liberation comes through hidden knowledge.",
  "Theosophy": "A 19th-century synthesis of Eastern and Western esotericism pursuing universal brotherhood and hidden laws of nature.",
  "Ceremonial Magic": "Structured ritual practice to invoke spiritual forces, using symbol, will, and correspondence.",
  "Divination": "Reading signs, symbols, or chance to access hidden knowledge — one of humanity's most universal practices.",
  "Neoplatonism": "A philosophical mysticism descending from Plato — reality as emanations from a transcendent One.",
  "Rosicrucianism": "A secret philosophical order claiming hidden wisdom about nature, health, and spiritual transformation.",
  "Freemasonry": "A fraternal tradition using symbolic ritual and allegory to transmit moral and philosophical teachings.",
  "Mystery Traditions": "Ancient initiatory schools — Eleusinian, Orphic, Mithraic — transmitting esoteric knowledge through ritual.",

  // Contemplative Traditions
  "Meditation": "Disciplined practices for focusing attention, cultivating awareness, and transforming the mind — found in all major traditions.",
  "Yoga Philosophy": "The Indian philosophical system of Patanjali and the Vedic tradition — union of body, mind, and consciousness.",
  "Zen Buddhism": "A Japanese school emphasizing direct experience over doctrine — the koan, the breath, the present moment.",
  "Sufism": "The mystical heart of Islam, seeking direct experience of the divine through love, poetry, and inner practice.",
  "Christian Mysticism": "A tradition within Christianity of direct experiential union with God — Meister Eckhart, St. John of the Cross.",
  "Taoism": "Chinese philosophy of living in harmony with the Tao — the ineffable principle underlying all change and existence.",
  "Advaita Vedanta": "Non-dual Hindu philosophy: ultimate reality is one undivided consciousness; the individual self is identical with Brahman.",
  "Contemplative Prayer": "Christian meditative practices — centering prayer, lectio divina — cultivating interior silence and union with God.",
  "Tantra": "Indian and Tibetan traditions using ritual, energy, and the body as a vehicle for spiritual transformation.",
  "Shamanic Traditions": "Indigenous healing practices involving altered states, spirit world navigation, and community ceremony.",
  "Lucid Dreaming": "The practice and study of becoming conscious within dreams — a bridge between sleep science and contemplative inquiry.",
  "Breathwork": "Intentional breathing practices — pranayama, holotropic breathing — altering physiology, emotion, and consciousness.",

  // Indigenous & Traditional Knowledge
  "Indigenous Cosmology": "Worldviews locating humans within a living cosmos — specific to place, language, and ancestral relationship.",
  "Ethnobotany": "Documents traditional plant knowledge — how cultures name, use, and relate to the plant world.",
  "Traditional Medicine": "Healing systems developed over millennia — Ayurveda, TCM, Indigenous medicine — integrating body, mind, and spirit.",
  "Oral Traditions": "Knowledge transmitted through story, song, and ceremony — memory systems without writing.",
  "Animism": "The worldview that all things — rivers, stones, animals, wind — possess spirit or agency.",
  "Totemism": "A system of symbolic kinship between human groups and animals, plants, or natural phenomena.",
  "Land Knowledge": "Deep, place-based ecological expertise accumulated over generations of intimate relationship with specific landscapes.",
  "Ethnoastronomy": "How indigenous cultures mapped, named, and related to the sky — navigation, calendars, ceremony.",
  "Ritual Studies": "Academic study of structured symbolic action — how ritual creates meaning, community, and transformation.",
  "Ancestor Veneration": "Practices honoring deceased family members as ongoing presences influencing the living — nearly universal across cultures.",
  "Sacred Ecology": "The view that nature is inherently sacred — integrating spiritual reverence with ecological care.",
  "Ethnoarchaeology": "Studies living cultures to interpret archaeological remains and bridge past and present human practices.",

  // Consciousness & Fringe
  "Consciousness Studies": "Interdisciplinary inquiry into subjective experience — the hard problem of why there is something it is like to be.",
  "Parapsychology": "Scientific investigation of claimed phenomena beyond conventional explanation — ESP, telekinesis, precognition.",
  "Psychedelic Science": "Research into psychedelic substances as tools for treating mental illness and studying consciousness.",
  "Near-Death Studies": "Examines near-death experiences — tunnel, light, life review — and their implications for consciousness.",
  "Dream Studies": "Scientific and phenomenological study of dreaming — REM sleep, dream content, and their psychological significance.",
  "Anomalous Cognition": "Investigates mental phenomena that challenge standard cognitive models — intuition, exceptional memory, altered states.",
  "Quantum Mind Theory": "Speculative frameworks proposing quantum processes in neurons underlie consciousness — Penrose-Hameroff and others.",
  "Morphic Resonance": "Rupert Sheldrake's controversial theory that memory is inherent in nature through non-local morphic fields.",
  "Noetics": "Studies the nature and potentials of consciousness, including its possible non-local and collective properties.",
  "Integral Theory": "Ken Wilber's framework synthesizing developmental psychology, spirituality, and systems theory into a unified worldview.",
  "Transpersonal Psychology": "Extends psychology beyond the personal self to include spiritual and transcendent aspects of human experience.",
  "Chronobiology": "Studies biological rhythms — circadian clocks, seasonal cycles — and how time is encoded in living systems.",
};

export const EDGES_DEF = [
  // Math <-> everything
  ["Mathematics","Statistics"],["Mathematics","Physics"],["Mathematics","Computer Science"],
  ["Mathematics","Logic"],["Mathematics","Probability Theory"],["Mathematics","Algebra"],
  ["Mathematics","Calculus"],["Mathematics","Geometry"],["Mathematics","Topology"],
  ["Mathematics","Number Theory"],["Mathematics","Graph Theory"],["Mathematics","Combinatorics"],
  ["Mathematics","Set Theory"],["Mathematics","Category Theory"],["Mathematics","Numerical Analysis"],
  ["Mathematics","Information Theory"],["Mathematics","Cryptography"],["Mathematics","Quantum Mechanics"],
  ["Mathematics","Statistical Physics"],["Mathematics","Economics"],
  ["Statistics","Epidemiology"],["Statistics","Psychology"],["Statistics","Data Science"],
  ["Statistics","Machine Learning"],["Statistics","Demography"],["Statistics","Sociology"],
  ["Statistics","Behavioral Economics"],["Statistics","Bioinformatics"],

  // Physics cluster
  ["Physics","Quantum Mechanics"],["Physics","Thermodynamics"],["Physics","Electromagnetism"],
  ["Physics","Relativity"],["Physics","Optics"],["Physics","Acoustics"],
  ["Physics","Particle Physics"],["Physics","Nuclear Physics"],["Physics","Astrophysics"],
  ["Physics","Cosmology"],["Physics","Statistical Physics"],["Physics","Condensed Matter"],
  ["Physics","Plasma Physics"],["Physics","Chemistry"],["Physics","Engineering & Tech"],
  ["Physics","Materials Science"],["Physics","Nanotechnology"],
  ["Quantum Mechanics","Particle Physics"],["Quantum Mechanics","Condensed Matter"],
  ["Quantum Mechanics","Physical Chemistry"],["Quantum Mechanics","Quantum Mechanics"],
  ["Astrophysics","Cosmology"],["Astrophysics","Relativity"],["Astrophysics","Astronomy"],
  ["Thermodynamics","Physical Chemistry"],["Thermodynamics","Meteorology"],
  ["Thermodynamics","Chemical Engineering"],["Electromagnetism","Electrical Engineering"],
  ["Electromagnetism","Optics"],["Electromagnetism","Telecommunications"],
  ["Nuclear Physics","Nuclear Physics"],["Particle Physics","Cosmology"],
  ["Statistical Physics","Complexity Science"],["Statistical Physics","Thermodynamics"],

  // Earth & Space
  ["Geology","Mineralogy"],["Geology","Seismology"],["Geology","Volcanology"],
  ["Geology","Paleontology"],["Geology","Geochemistry"],["Geology","Soil Science"],
  ["Geology","Geography"],["Oceanography","Marine Biology"],["Oceanography","Hydrology"],
  ["Oceanography","Climatology"],["Meteorology","Climatology"],["Meteorology","Environmental Science"],
  ["Climatology","Environmental Science"],["Climatology","Ecology"],
  ["Geography","Human Geography"],["Geography","Cartography"],["Geography","Urban Studies"],
  ["Astronomy","Astrophysics"],["Astronomy","Cosmology"],
  ["Paleontology","Evolutionary Biology"],["Soil Science","Agriculture"],
  ["Hydrology","Environmental Science"],["Glaciology","Climatology"],

  // Life Sciences
  ["Biology","Genetics"],["Biology","Ecology"],["Biology","Evolutionary Biology"],
  ["Biology","Microbiology"],["Biology","Zoology"],["Biology","Botany"],
  ["Biology","Cell Biology"],["Biology","Molecular Biology"],["Biology","Biochemistry"],
  ["Biology","Physiology"],["Biology","Taxonomy"],["Biology","Neuroscience"],
  ["Genetics","Molecular Biology"],["Genetics","Evolutionary Biology"],
  ["Genetics","Genomics"],["Genetics","Bioinformatics"],["Genetics","Medicine"],
  ["Ecology","Environmental Science"],["Ecology","Biodiversity"],["Ecology","Ethology"],
  ["Ecology","Marine Biology"],["Ecology","Systems Biology"],
  ["Evolutionary Biology","Anthropology"],["Evolutionary Biology","Paleontology"],
  ["Neuroscience","Cognitive Science"],["Neuroscience","Psychology"],
  ["Neuroscience","Neurology"],["Neuroscience","Psychiatry"],["Neuroscience","Neurophilosophy"],
  ["Neuroscience","Bioinformatics"],
  ["Cell Biology","Biochemistry"],["Cell Biology","Molecular Biology"],["Cell Biology","Immunology"],
  ["Molecular Biology","Bioinformatics"],["Molecular Biology","Biochemistry"],
  ["Biochemistry","Chemistry"],["Biochemistry","Pharmacology"],["Biochemistry","Toxicology"],
  ["Physiology","Medicine"],["Physiology","Anatomy"],
  ["Microbiology","Virology"],["Microbiology","Immunology"],["Microbiology","Biotechnology"],
  ["Immunology","Medicine"],["Virology","Epidemiology"],["Virology","Public Health"],

  // Chemistry
  ["Chemistry","Organic Chemistry"],["Chemistry","Inorganic Chemistry"],
  ["Chemistry","Physical Chemistry"],["Chemistry","Analytical Chemistry"],
  ["Chemistry","Electrochemistry"],["Chemistry","Polymer Chemistry"],
  ["Chemistry","Geochemistry"],["Chemistry","Astrochemistry"],
  ["Chemistry","Computational Chemistry"],["Chemistry","Toxicology"],
  ["Chemistry","Pharmacology"],["Organic Chemistry","Pharmacology"],
  ["Organic Chemistry","Biochemistry"],["Physical Chemistry","Thermodynamics"],
  ["Computational Chemistry","Computer Science"],

  // Medicine
  ["Medicine","Anatomy"],["Medicine","Pathology"],["Medicine","Surgery"],
  ["Medicine","Psychiatry"],["Medicine","Epidemiology"],["Medicine","Nutrition"],
  ["Medicine","Pharmacology (Med)"],["Medicine","Oncology"],["Medicine","Cardiology"],
  ["Medicine","Neurology"],["Medicine","Dermatology"],["Medicine","Radiology"],
  ["Medicine","Genetics (Med)"],["Medicine","Biotechnology"],["Medicine","Public Health"],
  ["Public Health","Epidemiology"],["Public Health","Sociology"],["Public Health","Nutrition"],
  ["Psychiatry","Psychology"],["Psychiatry","Neuroscience"],
  ["Pharmacology","Pharmacology (Med)"],["Pharmacology (Med)","Biotechnology"],
  ["Biomedical Engineering","Medicine"],["Biomedical Engineering","Biotechnology"],

  // Social Sciences
  ["Sociology","Psychology"],["Sociology","Anthropology"],["Sociology","Cultural Studies"],
  ["Sociology","Criminology"],["Sociology","Demography"],["Sociology","Urban Studies"],
  ["Psychology","Cognitive Science"],["Psychology","Social Psychology"],["Psychology","Behavioral Economics"],
  ["Psychology","Neuroscience"],["Psychology","Philosophy of Mind"],["Psychology","Education Theory"],
  ["Economics","Political Science"],["Economics","Behavioral Economics"],
  ["Economics","Demography"],["Economics","Urban Studies"],["Economics","International Relations"],
  ["Anthropology","Archaeology"],["Anthropology","Linguistics"],["Anthropology","Cultural Studies"],
  ["Anthropology","Mythology"],["Anthropology","Religion"],
  ["Political Science","International Relations"],["Political Science","Law"],
  ["Political Science","Political Philosophy"],["Political Science","Sociology"],
  ["Cognitive Science","Philosophy of Mind"],["Cognitive Science","Linguistics"],
  ["Cognitive Science","Artificial Intelligence"],["Cognitive Science","Neuroscience"],
  ["Communication","Sociology"],["Communication","Linguistics"],["Communication","Media Studies"],
  ["Human Geography","Urban Studies"],["Human Geography","Anthropology"],

  // Humanities
  ["Philosophy","Ethics"],["Philosophy","Epistemology"],["Philosophy","Metaphysics"],
  ["Philosophy","Logic"],["Philosophy","Aesthetics"],["Philosophy","Political Philosophy"],
  ["Philosophy","Philosophy of Science"],["Philosophy","Philosophy of Mind"],
  ["Philosophy","Hermeneutics"],["Philosophy","Semiotics"],["Philosophy","Religion"],
  ["History","Archaeology"],["History","Classics"],["History","Political Science"],
  ["History","Mythology"],["History","Cultural Studies"],["History","Art History"],
  ["Literature","Linguistics"],["Literature","Semiotics"],["Literature","Cultural Studies"],
  ["Literature","Aesthetics"],["Literature","Mythology"],["Literature","Classics"],
  ["Linguistics","Anthropology"],["Linguistics","Semiotics"],
  ["Ethics","Law"],["Ethics","Bioethics"],["Ethics","Political Philosophy"],
  ["Law","Political Science"],["Law","Ethics"],["Law","Criminology"],
  ["Epistemology","Philosophy of Science"],["Metaphysics","Philosophy of Mind"],

  // Arts
  ["Music","Acoustics"],["Music","Mathematics"],["Music","Cultural Studies"],
  ["Music","Cognitive Science"],["Music","Neuroscience"],
  ["Visual Art","Aesthetics"],["Visual Art","Graphic Design"],["Visual Art","Photography"],
  ["Architecture","Urban Design"],["Architecture","Engineering & Tech"],
  ["Architecture","Aesthetics"],["Architecture","Urban Studies"],
  ["Film & Cinema","Photography"],["Film & Cinema","Narrative Design"],
  ["Film & Cinema","Cultural Studies"],
  ["Game Design","Computer Science"],["Game Design","Narrative Design"],
  ["Game Design","Cognitive Science"],
  ["Graphic Design","Visual Art"],["Industrial Design","Mechanical Engineering"],
  ["Industrial Design","Graphic Design"],

  // Engineering & Tech
  ["Computer Science","Artificial Intelligence"],["Computer Science","Machine Learning"],
  ["Computer Science","Software Engineering"],["Computer Science","Cryptography"],
  ["Computer Science","Information Theory"],["Computer Science","Robotics"],
  ["Computer Science","Data Science"],["Computer Science","Information Science"],
  ["Artificial Intelligence","Machine Learning"],["Artificial Intelligence","Robotics"],
  ["Artificial Intelligence","Cognitive Science"],["Artificial Intelligence","Philosophy of Mind"],
  ["Artificial Intelligence","Data Science"],["Artificial Intelligence","Neuroscience"],
  ["Machine Learning","Data Science"],["Machine Learning","Statistics"],
  ["Machine Learning","Bioinformatics"],
  ["Electrical Engineering","Electromagnetism"],["Electrical Engineering","Telecommunications"],
  ["Electrical Engineering","Robotics"],["Electrical Engineering","Computer Science"],
  ["Mechanical Engineering","Materials Science"],["Mechanical Engineering","Thermodynamics"],
  ["Civil Engineering","Architecture"],["Civil Engineering","Materials Science"],
  ["Chemical Engineering","Chemistry"],["Chemical Engineering","Materials Science"],
  ["Aerospace Engineering","Fluid Dynamics"],["Aerospace Engineering","Materials Science"],
  ["Materials Science","Nanotechnology"],["Materials Science","Chemistry"],
  ["Robotics","Computer Science"],["Robotics","Mechanical Engineering"],
  ["Systems Theory","Cybernetics"],["Systems Theory","Complexity Science"],
  ["Environmental Engineering","Chemistry"],["Environmental Engineering","Environmental Science"],

  // Interdisciplinary
  ["Complexity Science","Systems Theory"],["Complexity Science","Biology"],
  ["Complexity Science","Sociology"],["Complexity Science","Economics"],
  ["Systems Biology","Biochemistry"],["Systems Biology","Genetics"],
  ["Systems Biology","Ecology"],
  ["Bioinformatics","Computer Science"],["Bioinformatics","Genetics"],
  ["Bioinformatics","Molecular Biology"],
  ["Environmental Science","Ecology"],["Environmental Science","Geography"],
  ["Environmental Science","Chemistry"],["Environmental Science","Climate Science"],
  ["Philosophy of Science","History"],["Philosophy of Science","Logic"],
  ["Philosophy of Mind","Neuroscience"],["Philosophy of Mind","Cognitive Science"],
  ["Neurophilosophy","Neuroscience"],["Neurophilosophy","Philosophy"],
  ["Data Science","Statistics"],["Data Science","Computer Science"],
  ["Cybernetics","Systems Theory"],["Cybernetics","Artificial Intelligence"],
  ["Information Science","Computer Science"],["Information Science","Cognitive Science"],
  ["Science & Tech Studies","History"],["Science & Tech Studies","Sociology"],

  // Esoteric & Occult
  ["Hermeticism","Alchemy"],["Hermeticism","Kabbalah"],["Hermeticism","Neoplatonism"],
  ["Hermeticism","Gnosticism"],["Hermeticism","Sacred Geometry"],["Hermeticism","Philosophy"],
  ["Hermeticism","Mystery Traditions"],["Hermeticism","Rosicrucianism"],
  ["Alchemy","Chemistry"],["Alchemy","Hermeticism"],["Alchemy","Philosophy"],
  ["Alchemy","Sacred Geometry"],
  ["Kabbalah","Gnosticism"],["Kabbalah","Numerology"],["Kabbalah","Sacred Geometry"],
  ["Kabbalah","Religion"],
  ["Astrology","Astronomy"],["Astrology","Mathematics"],["Astrology","Mythology"],
  ["Astrology","Divination"],["Astrology","Numerology"],
  ["Sacred Geometry","Mathematics"],["Sacred Geometry","Architecture"],["Sacred Geometry","Neoplatonism"],
  ["Gnosticism","Religion"],["Gnosticism","Philosophy"],["Gnosticism","Mythology"],
  ["Neoplatonism","Philosophy"],["Neoplatonism","Religion"],["Neoplatonism","Metaphysics"],
  ["Theosophy","Religion"],["Theosophy","Hermeticism"],["Theosophy","Philosophy"],["Theosophy","Anthropology"],
  ["Ceremonial Magic","Hermeticism"],["Ceremonial Magic","Kabbalah"],
  ["Divination","Mythology"],["Divination","Anthropology"],["Divination","Psychology"],
  ["Mystery Traditions","Religion"],["Mystery Traditions","Anthropology"],["Mystery Traditions","Mythology"],
  ["Tarot","Kabbalah"],["Tarot","Divination"],["Tarot","Psychology"],
  ["Numerology","Mathematics"],["Freemasonry","Hermeticism"],["Freemasonry","Sacred Geometry"],

  // Contemplative
  ["Meditation","Neuroscience"],["Meditation","Psychology"],["Meditation","Consciousness Studies"],
  ["Meditation","Zen Buddhism"],["Meditation","Yoga Philosophy"],["Meditation","Breathwork"],
  ["Yoga Philosophy","Advaita Vedanta"],["Yoga Philosophy","Tantra"],["Yoga Philosophy","Physiology"],
  ["Zen Buddhism","Taoism"],["Zen Buddhism","Philosophy"],["Zen Buddhism","Meditation"],
  ["Sufism","Religion"],["Sufism","Philosophy"],["Sufism","Christian Mysticism"],
  ["Christian Mysticism","Religion"],["Christian Mysticism","Philosophy"],["Christian Mysticism","Ethics"],
  ["Taoism","Philosophy"],["Taoism","Religion"],["Taoism","Traditional Medicine"],["Taoism","Ecology"],
  ["Advaita Vedanta","Philosophy"],["Advaita Vedanta","Epistemology"],["Advaita Vedanta","Consciousness Studies"],
  ["Tantra","Religion"],["Tantra","Sacred Geometry"],["Tantra","Yoga Philosophy"],
  ["Shamanic Traditions","Indigenous Cosmology"],["Shamanic Traditions","Ritual Studies"],
  ["Shamanic Traditions","Psychedelic Science"],["Shamanic Traditions","Anthropology"],
  ["Lucid Dreaming","Dream Studies"],["Lucid Dreaming","Consciousness Studies"],["Lucid Dreaming","Neuroscience"],
  ["Breathwork","Physiology"],["Breathwork","Psychology"],["Breathwork","Meditation"],

  // Indigenous
  ["Indigenous Cosmology","Mythology"],["Indigenous Cosmology","Animism"],
  ["Indigenous Cosmology","Ethnoastronomy"],["Indigenous Cosmology","Oral Traditions"],
  ["Ethnobotany","Botany"],["Ethnobotany","Anthropology"],["Ethnobotany","Traditional Medicine"],
  ["Ethnobotany","Ecology"],["Ethnobotany","Pharmacology"],
  ["Traditional Medicine","Medicine"],["Traditional Medicine","Ethnobotany"],
  ["Traditional Medicine","Pharmacology"],["Traditional Medicine","Anthropology"],
  ["Oral Traditions","Anthropology"],["Oral Traditions","Literature"],
  ["Oral Traditions","Linguistics"],["Oral Traditions","History"],
  ["Animism","Religion"],["Animism","Anthropology"],["Animism","Ecology"],
  ["Totemism","Animism"],["Totemism","Anthropology"],["Totemism","Psychology"],
  ["Land Knowledge","Geography"],["Land Knowledge","Ecology"],["Land Knowledge","Indigenous Cosmology"],
  ["Ethnoastronomy","Astronomy"],["Ethnoastronomy","Anthropology"],
  ["Ritual Studies","Anthropology"],["Ritual Studies","Religion"],["Ritual Studies","Sociology"],
  ["Ancestor Veneration","Religion"],["Ancestor Veneration","Anthropology"],
  ["Sacred Ecology","Ecology"],["Sacred Ecology","Indigenous Cosmology"],
  ["Sacred Ecology","Religion"],["Sacred Ecology","Environmental Science"],
  ["Ethnoarchaeology","Archaeology"],["Ethnoarchaeology","Anthropology"],

  // Consciousness & Fringe
  ["Consciousness Studies","Neuroscience"],["Consciousness Studies","Philosophy of Mind"],
  ["Consciousness Studies","Psychology"],["Consciousness Studies","Quantum Mind Theory"],
  ["Consciousness Studies","Meditation"],["Consciousness Studies","Noetics"],
  ["Consciousness Studies","Transpersonal Psychology"],
  ["Parapsychology","Psychology"],["Parapsychology","Anomalous Cognition"],["Parapsychology","Consciousness Studies"],
  ["Psychedelic Science","Neuroscience"],["Psychedelic Science","Psychology"],
  ["Psychedelic Science","Pharmacology"],["Psychedelic Science","Consciousness Studies"],
  ["Psychedelic Science","Anthropology"],
  ["Near-Death Studies","Consciousness Studies"],["Near-Death Studies","Neuroscience"],["Near-Death Studies","Psychology"],
  ["Dream Studies","Psychology"],["Dream Studies","Neuroscience"],
  ["Dream Studies","Consciousness Studies"],["Dream Studies","Mythology"],
  ["Quantum Mind Theory","Quantum Mechanics"],["Quantum Mind Theory","Neuroscience"],
  ["Quantum Mind Theory","Consciousness Studies"],["Quantum Mind Theory","Physics"],
  ["Noetics","Consciousness Studies"],["Noetics","Philosophy of Mind"],["Noetics","Parapsychology"],
  ["Integral Theory","Sociology"],["Integral Theory","Consciousness Studies"],
  ["Transpersonal Psychology","Psychology"],["Transpersonal Psychology","Consciousness Studies"],
  ["Transpersonal Psychology","Anthropology"],
  ["Morphic Resonance","Biology"],["Morphic Resonance","Consciousness Studies"],
  ["Chronobiology","Biology"],["Chronobiology","Neuroscience"],["Chronobiology","Physics"],
  ["Anomalous Cognition","Psychology"],["Anomalous Cognition","Parapsychology"],
];

// ─── 3D DOMAIN CLUSTER CENTERS ─────────────────────────────────────────────
export const DOMAIN_CENTERS = {
  "Formal Sciences":           [ 0,    430,   0  ],
  "Physical Sciences":         [ 350,  220,   0  ],
  "Earth & Space":             [ 220,  220,  310 ],
  "Life Sciences":             [-220,  80,   380 ],
  "Chemistry":                 [ 380,  80,   220 ],
  "Medicine & Health":         [-420,  80,   0  ],
  "Social Sciences":           [-220,  80,  -380 ],
  "Humanities":                [ 0,    80,  -430 ],
  "Arts & Design":             [-220, -200,  310 ],
  "Engineering & Tech":        [ 350,  220, -220 ],
  "Interdisciplinary":         [ 0,    0,    0  ],
  "Esoteric & Occult":         [-220, -300,  220 ],
  "Contemplative Traditions":  [ 0,   -430,  0  ],
  "Indigenous & Traditional":  [ 220, -300, -220 ],
  "Consciousness & Fringe":    [ 0,   -180, -380 ],
};
